// Datos referenciales DEMO. Completar marca solo cuando el negocio la confirme.
window.LUNA_PRODUCTOS = [
  {
    "id": 1,
    "nombre": "Alimento para perro adulto",
    "marca": "",
    "categoria": "perros",
    "subcategoria": "alimento",
    "peso": "3 kg",
    "precio": null,
    "precioAnterior": null,
    "imagen": "img/productos/alimento.svg",
    "destacado": true,
    "oferta": false,
    "disponible": null,
    "demo": true,
    "imagenFallback": "img/productos/alimento.svg"
  },
  {
    "id": 2,
    "nombre": "Alimento para gato adulto",
    "marca": "",
    "categoria": "gatos",
    "subcategoria": "alimento",
    "peso": "1,5 kg",
    "precio": null,
    "precioAnterior": null,
    "imagen": "img/productos/alimento.svg",
    "destacado": true,
    "oferta": false,
    "disponible": null,
    "demo": true,
    "imagenFallback": "img/productos/alimento.svg"
  },
  {
    "id": 3,
    "nombre": "Bocados de pollo",
    "marca": "",
    "categoria": "snacks",
    "subcategoria": "premios",
    "peso": "100 g",
    "precio": null,
    "precioAnterior": null,
    "imagen": "img/productos/snack.svg",
    "destacado": true,
    "oferta": false,
    "disponible": null,
    "demo": true,
    "imagenFallback": "img/productos/snack.svg"
  },
  {
    "id": 4,
    "nombre": "Collar ajustable turquesa",
    "marca": "",
    "categoria": "accesorios",
    "subcategoria": "collar",
    "peso": "Talla M",
    "precio": null,
    "precioAnterior": null,
    "imagen": "img/productos/collar.svg",
    "destacado": true,
    "oferta": false,
    "disponible": null,
    "demo": true,
    "imagenFallback": "img/productos/collar.svg"
  },
  {
    "id": 5,
    "nombre": "Alimento para cachorro",
    "marca": "",
    "categoria": "perros",
    "subcategoria": "alimento",
    "peso": "3 kg",
    "precio": null,
    "precioAnterior": null,
    "imagen": "img/productos/alimento.svg",
    "destacado": false,
    "oferta": false,
    "disponible": null,
    "demo": true,
    "imagenFallback": "img/productos/alimento.svg"
  },
  {
    "id": 6,
    "nombre": "Alimento para gatito",
    "marca": "",
    "categoria": "gatos",
    "subcategoria": "alimento",
    "peso": "1 kg",
    "precio": null,
    "precioAnterior": null,
    "imagen": "img/productos/alimento.svg",
    "destacado": false,
    "oferta": false,
    "disponible": null,
    "demo": true,
    "imagenFallback": "img/productos/alimento.svg"
  },
  {
    "id": 7,
    "nombre": "Premios de entrenamiento",
    "marca": "",
    "categoria": "snacks",
    "subcategoria": "premios",
    "peso": "150 g",
    "precio": null,
    "precioAnterior": null,
    "imagen": "img/productos/snack.svg",
    "destacado": false,
    "oferta": false,
    "disponible": null,
    "demo": true,
    "imagenFallback": "img/productos/snack.svg"
  },
  {
    "id": 8,
    "nombre": "Pelota para jugar",
    "marca": "",
    "categoria": "accesorios",
    "subcategoria": "juguetes",
    "peso": "7 cm",
    "precio": null,
    "precioAnterior": null,
    "imagen": "img/productos/pelota.svg",
    "destacado": false,
    "oferta": false,
    "disponible": null,
    "demo": true,
    "imagenFallback": "img/productos/pelota.svg"
  },
  {
    "id": 9,
    "nombre": "Shampoo para mascotas",
    "marca": "",
    "categoria": "higiene",
    "subcategoria": "shampoo",
    "peso": "250 ml",
    "precio": null,
    "precioAnterior": null,
    "imagen": "img/productos/higiene.svg",
    "destacado": false,
    "oferta": false,
    "disponible": null,
    "demo": true,
    "imagenFallback": "img/productos/higiene.svg"
  },
  {
    "id": 10,
    "nombre": "Arena sanitaria para gatos",
    "marca": "",
    "categoria": "higiene",
    "subcategoria": "arena",
    "peso": "4 kg",
    "precio": null,
    "precioAnterior": null,
    "imagen": "img/productos/arena.svg",
    "destacado": false,
    "oferta": false,
    "disponible": null,
    "demo": true,
    "imagenFallback": "img/productos/arena.svg"
  },
  {
    "id": 11,
    "nombre": "Bocados para gatos",
    "marca": "",
    "categoria": "snacks",
    "subcategoria": "premios",
    "peso": "60 g",
    "precio": null,
    "precioAnterior": null,
    "imagen": "img/productos/snack.svg",
    "destacado": false,
    "oferta": false,
    "disponible": null,
    "demo": true,
    "imagenFallback": "img/productos/snack.svg"
  },
  {
    "id": 12,
    "nombre": "Collar para gato",
    "marca": "",
    "categoria": "accesorios",
    "subcategoria": "collar",
    "peso": "Ajustable",
    "precio": null,
    "precioAnterior": null,
    "imagen": "img/productos/collar.svg",
    "destacado": false,
    "oferta": false,
    "disponible": null,
    "demo": true,
    "imagenFallback": "img/productos/collar.svg"
  }
];
