// Datos referenciales DEMO. Completar marca solo cuando el negocio la confirme.
window.LUNA_PRODUCTOS = [
  {
    "id": 1,
    "nombre": "Alimento para perro adulto",
    "marca": "",
    "categoria": "perros",
    "subcategoria": "alimento",
    "peso": "3 kg",
    "precio": null,
    "precioAnterior": null,
    "imagen": "img/productos/alimento.svg",
    "destacado": true,
    "oferta": false,
    "disponible": null,
    "demo": true,
    "imagenFallback": "img/productos/alimento.svg"
  },
  {
    "id": 2,
    "nombre": "Alimento para gato adulto",
    "marca": "",
    "categoria": "gatos",
    "subcategoria": "alimento",
    "peso": "1,5 kg",
    "precio": null,
    "precioAnterior": null,
    "imagen": "img/productos/alimento.svg",
    "destacado": true,
    "oferta": false,
    "disponible": null,
    "demo": true,
    "imagenFallback": "img/productos/alimento.svg"
  },
  {
    "id": 3,
    "nombre": "Bocados de pollo",
    "marca": "",
    "categoria": "snacks",
    "subcategoria": "premios",
    "peso": "100 g",
    "precio": null,
    "precioAnterior": null,
    "imagen": "img/productos/snack.svg",
    "destacado": true,
    "oferta": false,
    "disponible": null,
    "demo": true,
    "imagenFallback": "img/productos/snack.svg"
  },
  {
    "id": 4,
    "nombre": "Collar ajustable turquesa",
    "marca": "",
    "categoria": "accesorios",
    "subcategoria": "collar",
    "peso": "Talla M",
    "precio": null,
    "precioAnterior": null,
    "imagen": "img/productos/collar.svg",
    "destacado": true,
    "oferta": false,
    "disponible": null,
    "demo": true,
    "imagenFallback": "img/productos/collar.svg"
  },
  {
    "id": 5,
    "nombre": "Alimento para cachorro",
    "marca": "",
    "categoria": "perros",
    "subcategoria": "alimento",
    "peso": "3 kg",
    "precio": null,
    "precioAnterior": null,
    "imagen": "img/productos/alimento.svg",
    "destacado": false,
    "oferta": false,
    "disponible": null,
    "demo": true,
    "imagenFallback": "img/productos/alimento.svg"
  },
  {
    "id": 6,
    "nombre": "Alimento para gatito",
    "marca": "",
    "categoria": "gatos",
    "subcategoria": "alimento",
    "peso": "1 kg",
    "precio": null,
    "precioAnterior": null,
    "imagen": "img/productos/alimento.svg",
    "destacado": false,
    "oferta": false,
    "disponible": null,
    "demo": true,
    "imagenFallback": "img/productos/alimento.svg"
  },
  {
    "id": 7,
    "nombre": "Premios de entrenamiento",
    "marca": "",
    "categoria": "snacks",
    "subcategoria": "premios",
    "peso": "150 g",
    "precio": null,
    "precioAnterior": null,
    "imagen": "img/productos/snack.svg",
    "destacado": false,
    "oferta": false,
    "disponible": null,
    "demo": true,
    "imagenFallback": "img/productos/snack.svg"
  },
  {
    "id": 8,
    "nombre": "Pelota para jugar",
    "marca": "",
    "categoria": "accesorios",
    "subcategoria": "juguetes",
    "peso": "7 cm",
    "precio": null,
    "precioAnterior": null,
    "imagen": "img/productos/pelota.svg",
    "destacado": false,
    "oferta": false,
    "disponible": null,
    "demo": true,
    "imagenFallback": "img/productos/pelota.svg"
  },
  {
    "id": 9,
    "nombre": "Shampoo para mascotas",
    "marca": "",
    "categoria": "higiene",
    "subcategoria": "shampoo",
    "peso": "250 ml",
    "precio": null,
    "precioAnterior": null,
    "imagen": "img/productos/higiene.svg",
    "destacado": false,
    "oferta": false,
    "disponible": null,
    "demo": true,
    "imagenFallback": "img/productos/higiene.svg"
  },
  {
    "id": 10,
    "nombre": "Arena sanitaria para gatos",
    "marca": "",
    "categoria": "higiene",
    "subcategoria": "arena",
    "peso": "4 kg",
    "precio": null,
    "precioAnterior": null,
    "imagen": "img/productos/arena.svg",
    "destacado": false,
    "oferta": false,
    "disponible": null,
    "demo": true,
    "imagenFallback": "img/productos/arena.svg"
  },
  {
    "id": 11,
    "nombre": "Bocados para gatos",
    "marca": "",
    "categoria": "snacks",
    "subcategoria": "premios",
    "peso": "60 g",
    "precio": null,
    "precioAnterior": null,
    "imagen": "img/productos/snack.svg",
    "destacado": false,
    "oferta": false,
    "disponible": null,
    "demo": true,
    "imagenFallback": "img/productos/snack.svg"
  },
  {
    "id": 12,
    "nombre": "Collar para gato",
    "marca": "",
    "categoria": "accesorios",
    "subcategoria": "collar",
    "peso": "Ajustable",
    "precio": null,
    "precioAnterior": null,
    "imagen": "img/productos/collar.svg",
    "destacado": false,
    "oferta": false,
    "disponible": null,
    "demo": true,
    "imagenFallback": "img/productos/collar.svg"
  }
];

// Productos adicionales DEMO (IDs 13–66). Precios ficticios en pesos chilenos.
// Los 12 objetos anteriores se conservan completos, con sus precios pendientes.
// Para ampliar el catálogo, agrega un objeto con un ID único a esta lista.
window.LUNA_PRODUCTOS.push(...[
  { id: 13, nombre: 'Alimento premium para perro adulto', categoria: 'perros', subcategoria: 'alimento', peso: '10 kg', precio: 38990, imagen: 'img/productos/alimento.svg' },
  { id: 14, nombre: 'Alimento para perro senior', categoria: 'perros', subcategoria: 'alimento', peso: '7 kg', precio: 28990, imagen: 'img/productos/alimento.svg' },
  { id: 15, nombre: 'Alimento para cachorro raza pequeña', categoria: 'perros', subcategoria: 'alimento', peso: '3 kg', precio: 14990, imagen: 'img/productos/alimento.svg' },
  { id: 16, nombre: 'Alimento para cachorro raza grande', categoria: 'perros', subcategoria: 'alimento', peso: '15 kg', precio: 45990, imagen: 'img/productos/alimento.svg' },
  { id: 17, nombre: 'Alimento húmedo para perro con pollo', categoria: 'perros', subcategoria: 'alimento húmedo', peso: '400 g', precio: 2490, imagen: 'img/productos/alimento.svg' },
  { id: 18, nombre: 'Alimento húmedo para perro con pavo', categoria: 'perros', subcategoria: 'alimento húmedo', peso: '400 g', precio: 2490, imagen: 'img/productos/alimento.svg' },
  { id: 19, nombre: 'Alimento para perro de raza pequeña', categoria: 'perros', subcategoria: 'alimento', peso: '3 kg', precio: 15990, imagen: 'img/productos/alimento.svg' },
  { id: 20, nombre: 'Alimento para perro de raza grande', categoria: 'perros', subcategoria: 'alimento', peso: '18 kg', precio: 49990, imagen: 'img/productos/alimento.svg' },
  { id: 21, nombre: 'Alimento para perro adulto con cordero', categoria: 'perros', subcategoria: 'alimento', peso: '10 kg', precio: 39990, imagen: 'img/productos/alimento.svg' },
  { id: 22, nombre: 'Alimento para perro adulto con salmón', categoria: 'perros', subcategoria: 'alimento', peso: '10 kg', precio: 42990, imagen: 'img/productos/alimento.svg' },
  { id: 23, nombre: 'Alimento premium para gato adulto', categoria: 'gatos', subcategoria: 'alimento', peso: '3 kg', precio: 16990, imagen: 'img/productos/alimento.svg' },
  { id: 24, nombre: 'Alimento para gato esterilizado', categoria: 'gatos', subcategoria: 'alimento', peso: '7 kg', precio: 31990, imagen: 'img/productos/alimento.svg' },
  { id: 25, nombre: 'Alimento para gato senior', categoria: 'gatos', subcategoria: 'alimento', peso: '3 kg', precio: 17990, imagen: 'img/productos/alimento.svg' },
  { id: 26, nombre: 'Alimento para gatito indoor', categoria: 'gatos', subcategoria: 'alimento', peso: '1,5 kg', precio: 10990, imagen: 'img/productos/alimento.svg' },
  { id: 27, nombre: 'Alimento para gato indoor', categoria: 'gatos', subcategoria: 'alimento', peso: '3 kg', precio: 16990, imagen: 'img/productos/alimento.svg' },
  { id: 28, nombre: 'Alimento para gato adulto con salmón', categoria: 'gatos', subcategoria: 'alimento', peso: '8 kg', precio: 32990, imagen: 'img/productos/alimento.svg' },
  { id: 29, nombre: 'Alimento para gato adulto con pollo', categoria: 'gatos', subcategoria: 'alimento', peso: '8 kg', precio: 29990, imagen: 'img/productos/alimento.svg' },
  { id: 30, nombre: 'Alimento para gato esterilizado en bolsa pequeña', categoria: 'gatos', subcategoria: 'alimento', peso: '1,5 kg', precio: 10990, imagen: 'img/productos/alimento.svg' },
  { id: 31, nombre: 'Alimento húmedo para gato con atún', categoria: 'gatos', subcategoria: 'alimento húmedo', peso: '85 g', precio: 1290, imagen: 'img/productos/alimento.svg' },
  { id: 32, nombre: 'Alimento húmedo para gato con pollo', categoria: 'gatos', subcategoria: 'alimento húmedo', peso: '85 g', precio: 1190, imagen: 'img/productos/alimento.svg' },
  { id: 33, nombre: 'Alimento húmedo para gato joven', categoria: 'gatos', subcategoria: 'alimento húmedo', peso: '100 g', precio: 1490, imagen: 'img/productos/alimento.svg' },
  { id: 34, nombre: 'Rascador compacto para gato', categoria: 'gatos', subcategoria: 'rascadores', peso: 'Unidad', precio: 12990, imagen: 'img/productos/placeholder.svg' },
  { id: 35, nombre: 'Rascador tipo torre para gato', categoria: 'gatos', subcategoria: 'rascadores', peso: 'Unidad', precio: 34990, imagen: 'img/productos/placeholder.svg' },
  { id: 36, nombre: 'Cama tipo cueva para gato', categoria: 'gatos', subcategoria: 'camas', peso: '40 cm', precio: 18990, imagen: 'img/productos/placeholder.svg' },
  { id: 37, nombre: 'Transportadora para gato', categoria: 'gatos', subcategoria: 'transportadoras', peso: 'Mediana', precio: 24990, imagen: 'img/productos/placeholder.svg' },
  { id: 38, nombre: 'Caña de juego para gato', categoria: 'gatos', subcategoria: 'juguetes', peso: '45 cm', precio: 3990, imagen: 'img/productos/pelota.svg' },
  { id: 39, nombre: 'Ratones de tela para gato', categoria: 'gatos', subcategoria: 'juguetes', peso: 'Pack de 3', precio: 2990, imagen: 'img/productos/pelota.svg' },
  { id: 40, nombre: 'Bebedero para gato', categoria: 'gatos', subcategoria: 'bebederos', peso: '700 ml', precio: 6990, imagen: 'img/productos/placeholder.svg' },
  { id: 41, nombre: 'Snack dental para perros', categoria: 'snacks', subcategoria: 'premios dentales', peso: '200 g', precio: 5990, imagen: 'img/productos/snack.svg' },
  { id: 42, nombre: 'Premios de entrenamiento con pollo', categoria: 'snacks', subcategoria: 'premios', peso: '250 g', precio: 4990, imagen: 'img/productos/snack.svg' },
  { id: 43, nombre: 'Tiras de carne para perros', categoria: 'snacks', subcategoria: 'premios', peso: '150 g', precio: 3990, imagen: 'img/productos/snack.svg' },
  { id: 44, nombre: 'Galletas para perro adulto', categoria: 'snacks', subcategoria: 'galletas', peso: '300 g', precio: 3490, imagen: 'img/productos/snack.svg' },
  { id: 45, nombre: 'Premios blandos para cachorro', categoria: 'snacks', subcategoria: 'premios', peso: '100 g', precio: 2990, imagen: 'img/productos/snack.svg' },
  { id: 46, nombre: 'Snack cremoso para gatos', categoria: 'snacks', subcategoria: 'premios', peso: 'Pack de 4 × 14 g', precio: 2990, imagen: 'img/productos/snack.svg' },
  { id: 47, nombre: 'Bocados de salmón para gatos', categoria: 'snacks', subcategoria: 'premios', peso: '80 g', precio: 2490, imagen: 'img/productos/snack.svg' },
  { id: 48, nombre: 'Arnés ajustable turquesa', categoria: 'accesorios', subcategoria: 'arneses', peso: 'Talla M', precio: 12990, imagen: 'img/productos/collar.svg' },
  { id: 49, nombre: 'Correa de paseo', categoria: 'accesorios', subcategoria: 'correas', peso: '1,5 m', precio: 7990, imagen: 'img/productos/collar.svg' },
  { id: 50, nombre: 'Collar reflectante', categoria: 'accesorios', subcategoria: 'collares', peso: 'Talla L', precio: 6990, imagen: 'img/productos/collar.svg' },
  { id: 51, nombre: 'Pelota interactiva', categoria: 'accesorios', subcategoria: 'juguetes', peso: '8 cm', precio: 4990, imagen: 'img/productos/pelota.svg' },
  { id: 52, nombre: 'Mordedor de goma', categoria: 'accesorios', subcategoria: 'juguetes', peso: '15 cm', precio: 6990, imagen: 'img/productos/pelota.svg' },
  { id: 53, nombre: 'Cama acolchada para perro', categoria: 'accesorios', subcategoria: 'camas', peso: '60 × 45 cm', precio: 29990, imagen: 'img/productos/placeholder.svg' },
  { id: 54, nombre: 'Plato doble de acero', categoria: 'accesorios', subcategoria: 'platos', peso: '2 × 500 ml', precio: 9990, imagen: 'img/productos/placeholder.svg' },
  { id: 55, nombre: 'Arena aglomerante para gatos', categoria: 'higiene', subcategoria: 'arena sanitaria', peso: '10 kg', precio: 14990, imagen: 'img/productos/arena.svg' },
  { id: 56, nombre: 'Arena vegetal para gatos', categoria: 'higiene', subcategoria: 'arena sanitaria', peso: '6 kg', precio: 11990, imagen: 'img/productos/arena.svg' },
  { id: 57, nombre: 'Shampoo neutro para mascotas', categoria: 'higiene', subcategoria: 'shampoo', peso: '500 ml', precio: 6990, imagen: 'img/productos/higiene.svg' },
  { id: 58, nombre: 'Toallitas húmedas para mascotas', categoria: 'higiene', subcategoria: 'limpieza', peso: '50 unidades', precio: 3990, imagen: 'img/productos/higiene.svg' },
  { id: 59, nombre: 'Cepillo para mascotas', categoria: 'higiene', subcategoria: 'cepillos', peso: 'Unidad', precio: 5990, imagen: 'img/productos/higiene.svg' },
  { id: 60, nombre: 'Bolsas para paseo', categoria: 'higiene', subcategoria: 'limpieza', peso: 'Pack de 6 rollos', precio: 3490, imagen: 'img/productos/higiene.svg' },
  // Ropa de muestra. Modelos, tallas y disponibilidad reales pendientes de confirmar.
  { id: 61, nombre: 'Polerón para perros', categoria: 'ropa', subcategoria: 'polerones', peso: 'Talla S', precio: 14990, imagen: 'img/productos/ropa.svg' },
  { id: 62, nombre: 'Parka impermeable para perros', categoria: 'ropa', subcategoria: 'abrigos', peso: 'Talla M', precio: 19990, imagen: 'img/productos/ropa.svg' },
  { id: 63, nombre: 'Chaleco tejido para perros', categoria: 'ropa', subcategoria: 'chalecos', peso: 'Talla L', precio: 12990, imagen: 'img/productos/ropa.svg' },
  { id: 64, nombre: 'Polera para perros', categoria: 'ropa', subcategoria: 'poleras', peso: 'Talla S', precio: 8990, imagen: 'img/productos/ropa.svg' },
  { id: 65, nombre: 'Chaleco liviano para gatos', categoria: 'ropa', subcategoria: 'chalecos', peso: 'Talla S', precio: 11990, imagen: 'img/productos/ropa.svg' },
  { id: 66, nombre: 'Polera suave para gatos', categoria: 'ropa', subcategoria: 'poleras', peso: 'Talla XS', precio: 8990, imagen: 'img/productos/ropa.svg' }
].map(product => ({ marca: '', precioAnterior: null, destacado: false, oferta: false, disponible: null, demo: true, ...product, imagenFallback: product.imagen })));
